blog/blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from blog.settings import STATIC_ROOT
from personal_blog.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal_blog.urls')),  # 添加主路由
    path('', include('comments.urls')),  # 评论
    path('all/rss/', AllPostsRssFeed(), name='rss'),  # Rss订阅
    path('mdeditor/', include('mdeditor.urls')),
    url(r'^static/(?P<path>.*)/$', serve, {'document_root': STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/personal_blog/urls.py
from django.urls import path

import personal_blog
from . import views

app_name = 'personal_blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),  # 主页
    path('posts/<int:pk>/', views.DetailView.as_view(), name='detail'),  # 详情页
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),  # 归档页
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),  # 分类页
    path('tags/<int:pk>/', views.TagsView.as_view(), name='tags'),
    path('full-width/', views.BlogView.as_view(), name='full-width'),  # 博客
    path('about/', views.AboutView.as_view(), name='about'),  # 关于
    path('contact/', views.ContactView.as_view(), name='contact'),  # 联系
    path('search/', views.SearchView.as_view(), name='search'),  # 全文搜索
]

handler404 = personal_blog.views.page_not_found

blog/templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>竹也的 &amp; 小屋</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'personal_blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'personal_blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'personal_blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'personal_blog/css/highlights/default.css' %}">

    <!-- js -->
    <script src="{% static 'personal_blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'personal_blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'personal_blog/js/pace.min.js' %}"></script>
    <script src="{% static 'personal_blog/js/modernizr.custom.js' %}"></script>
    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }

        .pagination-simple {
            text-align: center;
        }
    </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'personal_blog:index' %}"><b>竹也的</b> &amp; 小屋</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'personal_blog:index' %}" data-hover="首页">首页</a>
                            </li>
                            <li class="cl-effect-11"><a href="{% url 'personal_blog:full-width' %}"
                                                        data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'personal_blog:about' %}" data-hover="关于">关于</a>
                            </li>
                            <li class="cl-effect-11"><a href="{% url 'personal_blog:contact' %}" data-hover="联系">联系</a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'personal_blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}

                {% show_recent_posts %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}

                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 公交车司机终于在众人的谴责中将座位让给了老太太</p>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'personal_blog/js/script.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>